### PR TITLE
Replacing runtimeIncrementer with ctr specific incrementer

### LINKED ISSUE #4684: CTR throws DuplicateKeyException when same CTR instance is run concurrently
Composed Task Runner throws a DuplicateKeyException for constraint `job_inst_un`, when multiple instances of the same composed task definition are run simultaneosly.   This is because the runIdIncrementer with the `ISOLATION_REPEATABLE_READ` transaction isolation allow multiple reads of the same job parameters.  
To resolve this we need to create a new incrementer that will use UUID instead of a sequence.

### PR DESCRIPTION
**Pull request by cppwfs**
resolves #4684

### CODE REVIEW

File: spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedRunnerJobFactory.java [hunk 1]
```diff
@@ -352,4 +356,13 @@ private Flow getTaskAppFlow(TaskAppNode taskApp) {
 
 		return new FlowBuilder<Flow>(beanName).from(currentStep).end();
 	}
+
+	public static class UuidIncrementer implements JobParametersIncrementer {
+
+		@Override
+		public JobParameters getNext(JobParameters parameters) {
+			JobParameters params = (parameters == null) ? new JobParameters() : parameters;
+			return new JobParametersBuilder(params).addString(CTR_KEY, UUID.randomUUID().toString()).toJobParameters();
```
Comment (jvalkeal) [inline spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedRunnerJobFactory.java:365]: So this doesn't cause any trouble that key is suddenly changed from `run.id` to `ctr.id` and type from long to string?

Comment (cppwfs) [reply spring-cloud-dataflow-composed-task-runner/src/main/java/org/springframework/cloud/dataflow/composedtaskrunner/ComposedRunnerJobFactory.java:365]: Not for batch or CTR.   However, if users are somehow useing the run.id property it could be an issue for them.   We could add a property that allows users to enable the use of UUID versus the default run id incrementer.   Thoughts?

**Comment by cppwfs** [comment]
Updated with new option.
