### PR TITLE
Use custom paging provider for aggregate DAO queries

### LINKED ISSUE #5531: Unable to navigate through the job execution pages
Also you can't navigate through the job execution pages anymore. 

org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT E.JOB_EXECUTION_ID FROM (SELECT E.JOB_EXECUTION_ID, ROWNUM as TMP_ROW_NUM FROM (SELECT E.JOB_EXECUTION_ID FROM AGGREGATE_JOB_INSTANCE I JOIN AGGREGATE_JOB_EXECUTION E ON I.JOB_INSTANCE_ID=E.JOB_INSTANCE_ID AND I.SCHEMA_TARGET=E.SCHEMA_TARGET JOIN AGGREGATE_TASK_BATCH B ON E.JOB_EXECUTION_ID = B.JOB_EXECUTION_ID AND E.SCHEMA_TARGET = B.SCHEMA_TARGET JOIN AGGREGATE_TASK_EXECUTION T ON B.TASK_EXECUTION_ID = T.TASK_EXECUTION_ID AND B.SCHEMA_TARGET = T.SCHEMA_TARGET ORDER BY E.JOB_EXECUTION_ID DESC)) WHERE TMP_ROW_NUM = 20]; nested exception is java.sql.SQLSyntaxErrorException: ORA-00904: \"E\".\"JOB_EXECUTION_ID\": ungültige ID

_Originally posted by @klopfdreh in https://github.com/spring-cloud/spring-cloud-dataflow/issues/5524#issuecomment-1774833293_

### PR DESCRIPTION
**Pull request by onobc**
This commit adds a custom Oracle/MSSQl/DB2 paging provider that is used only by the aggregate DAO. This is required because the standard paging provider that ships with Spring Batch 4.x does not properly handle sort key aliases when using nested ROW_NUMBER clauses for these databases.

Resolves #5531

### CODE REVIEW

File: spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java [hunk 1]
```diff
@@ -830,4 +836,121 @@ private boolean determineSupportsRowNumberFunction(DataSource dataSource) {
 		}
 		return false;
 	}
+
+	/**
+	 * A {@link SqlPagingQueryProviderFactoryBean} specialization that overrides the {@code Oracle} paging
+	 * {@link SafeOraclePagingQueryProvider provider} with an implementation that properly handles sort aliases.
+	 * <p><b>NOTE:</b> nested within the aggregate DAO as this is the only place that needs this specialization.
+	 */
+	static class SafeSqlPagingQueryProviderFactoryBean extends SqlPagingQueryProviderFactoryBean {
```
Comment (onobc) [inline spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java:845]: I decided to extend the base instead of copy/pasta the entire Batch 4.x impl. 
I then just hijack the returned provider and wrap it in a delegate that inspects its set fields.

File: spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java [hunk 2]
```diff
@@ -830,4 +836,121 @@ private boolean determineSupportsRowNumberFunction(DataSource dataSource) {
...
+
+	/**
+	 * A {@link AbstractSqlPagingQueryProvider paging provider} for {@code Oracle} that works around the fact that the
+	 * Oracle provider in Spring Batch 4.x does not properly handle sort aliases when using nested {@code ROW_NUMBER}
+	 * clauses.
+	 */
+	static class SafeOraclePagingQueryProvider extends AbstractSqlPagingQueryProvider {
+
+		SafeOraclePagingQueryProvider(AbstractSqlPagingQueryProvider delegate, DataSource dataSource) {
+			// Have to use reflection to retrieve the provider fields
```
Comment (onobc) [inline spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java:874]: Yes, gross. However, no other means to access these fields short of submitting change to Batch 4.x

File: spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java [hunk 3]
```diff
@@ -830,4 +836,121 @@ private boolean determineSupportsRowNumberFunction(DataSource dataSource) {
...
+			}
+			if (StringUtils.hasText(this.getGroupClause())) {
+				sql.append(" GROUP BY ").append(this.getGroupClause());
+			}
+			// inner sort by
+			sql.append(" ORDER BY ").append(SqlPagingQueryUtils.buildSortClause(this));
+			sql.append(") WHERE ").append("ROWNUM <= " + pageSize);
+			if (remainingPageQuery) {
+				sql.append(" AND ");
+				// For the outer sort we want to use sort keys w/o aliases. However,
```
Comment (onobc) [inline spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java:939]: Of course the proper option is to submit a change to Batch 4.x that allows one to pass in the sort keys. If that is viable and 4.x is not EOL then we should do that and remove this hack once its available in 4.x

File: spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java [hunk 4]
```diff
@@ -830,4 +836,121 @@ private boolean determineSupportsRowNumberFunction(DataSource dataSource) {
...
+		}
+
+	}
+
+	/**
+	 * A {@link AbstractSqlPagingQueryProvider paging provider} for {@code Oracle} that works around the fact that the
+	 * Oracle provider in Spring Batch 4.x does not properly handle sort aliases when using nested {@code ROW_NUMBER}
+	 * clauses.
+	 */
+	static class SafeOraclePagingQueryProvider extends AbstractSqlPagingQueryProvider {
```
Comment (onobc) [inline spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java:871]: NOTE: The whole reason this exists is to get around the issues that @klopfdreh found in https://github.com/spring-cloud/spring-cloud-dataflow/issues/5524#issuecomment-1778630171. 

@cppwfs should we raise these as issues in Batch 4.x ? I am surprised they have not been reported already. Is 4.x EOL or would it make sense to update these in Batch 4.x? If we do, then we should contribute this fix and then remove this patched code here once the proper fix is available.

File: spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/AbstractSmokeTest.java [hunk 5]
```diff
@@ -164,6 +164,12 @@ void shouldListJobExecutionsUsingPerformantRowNumberQuery(
 				"as STEP_COUNT FROM AGGREGATE_JOB_INSTANCE";
 		Awaitility.waitAtMost(Duration.ofSeconds(5))
 				.untilAsserted(() -> assertThat(output).contains(expectedSqlFragment));
+
+		// Verify that paging works as well
```
Comment (onobc) [inline spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/AbstractSmokeTest.java:168]: Super fortunate that our smoke tests now cover this API - we get these paging tests against Oracle for basically free.

File: spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/JobExecutionTestUtils.java [hunk 6]
```diff
@@ -130,4 +137,37 @@ private JobExecution saveJobExecution(JobExecution jobExecution, JdbcTemplate jd
 	private Timestamp timestampFromDate(Date date) {
 		return (date != null) ? Timestamp.valueOf(date.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime()) : null;
 	}
+
+
+	/**
+	 * Test utility that generates hundreds of job executions which can be useful when debugging paging issues.
+	 * <p>To run, adjust the datasource properties accordingly and then execute the test manually in your editor.
+	 */
+	@Disabled
```
Comment (onobc) [inline spring-cloud-dataflow-server/src/test/java/org/springframework/cloud/dataflow/server/db/migration/JobExecutionTestUtils.java:146]: I left this utility in the test code and disabled. This allowed me to quickly populate hundreds of boot2+boot3 job executions. It is `@Disabled` so it will not run during normal test runs **BUT** we can manually run the test method below to generate the data when needed. Wdyt?

**Comment by corneil** [comment]
From `org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java:607` in org.springframework.batch.item.database.support.AbstractSqlPagingQueryProvider#getSortKeysWithoutAliases
`return SqlPagingQueryUtils.buildSortClause(provider.getSortKeysWithoutAliases());` causes:


`SELECT TMP_SUB.JOB_EXECUTION_ID FROM ( SELECT E.JOB_EXECUTION_ID, ROW_NUMBER() OVER ( ORDER BY **JOB_EXECUTION_ID** DESC) AS ROW_NUMBER FROM`
resulting in `com.microsoft.sqlserver.jdbc.SQLServerException: Ambiguous column name 'JOB_EXECUTION_ID'`


The offending code is a part of batch framework.

**Comment by corneil** [comment]
DB2 seems to suffer the same error.

File: spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java (hunk 3 above)
Comment (cppwfs) [reply spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java:939]: Spring Batch 4.x is EOL :-(

**Review by cppwfs — COMMENTED** [review]
On the code side it looks good.   The tests you added catch DB2 and SqlServer has an ambiguous jobexecution id like corneil mentioned from batch 4.  And your updated tests now catch this scenario.   Yeah for your newly added smoke tests!

File: spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java (hunk 3 above)
Comment (onobc) [reply spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java:939]: This is what I thought and also influenced my approach here.

File: spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java (hunk 4 above)
Comment (onobc) [reply spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java:871]: Based on the additional failures in DB2 and SQLServer I am not convinced this is an issue in Batch as much as an issue of our usage.

File: spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java [hunk 7]
```diff
@@ -830,4 +836,121 @@ private boolean determineSupportsRowNumberFunction(DataSource dataSource) {
...
+			Map<String, Order> sortKeys = (withAliases) ? this.getSortKeys() : this.getSortKeysWithoutAliases();
+			sql.append(sortKeys.keySet().stream().collect(Collectors.joining(",")));
+			return sql.toString();
+		}
+
+		// Taken from SqlPagingQueryUtils.generateRowNumSqlQuery but use sortKeysWithoutAlias
+		// for outer sort condition.
+		private String generateRowNumSqlQuery(boolean remainingPageQuery, int pageSize) {
+			StringBuilder sql = new StringBuilder();
+			sql.append("SELECT * FROM (SELECT ").append(getSelectClause());
```
[the remark this answers is not in the document]
Comment (onobc) [reply spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java:926]: Taken from the base implementation in Batch - I will noodle it a bit and see if there is value in enumerating.

**Comment by onobc** [comment]
> From `org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java:607` in org.springframework.batch.item.database.support.AbstractSqlPagingQueryProvider#getSortKeysWithoutAliases `return SqlPagingQueryUtils.buildSortClause(provider.getSortKeysWithoutAliases());` causes:
> 
> `SELECT TMP_SUB.JOB_EXECUTION_ID FROM ( SELECT E.JOB_EXECUTION_ID, ROW_NUMBER() OVER ( ORDER BY **JOB_EXECUTION_ID** DESC) AS ROW_NUMBER FROM` resulting in `com.microsoft.sqlserver.jdbc.SQLServerException: Ambiguous column name 'JOB_EXECUTION_ID'`
> 
> The offending code is a part of batch framework.

Right, but there is a possibility of our usage upstream is causing this to surface.

File: spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java [hunk 8]
```diff
@@ -809,12 +814,13 @@ private PagingQueryProvider getPagingQueryProvider(String fields, String fromCla
 		}
 		if (fields.contains("E.JOB_EXECUTION_ID") && this.useRowNumberOptimization) {
 			Order order = sortKeys.get("E.JOB_EXECUTION_ID");
-			String orderString = Optional.ofNullable(order).map(orderKey -> orderKey == Order.DESCENDING ? "DESC" : "ASC").orElse("DESC");
```
Comment (corneil) [inline spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java:812]: How about:
```java
String orderString = order == null || order == Order.DESCENDING ? "DESC" : "ASC";
```

**Review by corneil — APPROVED** [review]

**Review by cppwfs — CHANGES_REQUESTED** [review]

File: README.md [hunk 9]
```diff
@@ -113,6 +113,19 @@ You can follow the steps in the [MSSQL on Mac ARM64](https://github.com/spring-c
...
 ----
 
+## Running Locally w/ IBM DB2
+By default, the Dataflow server jar does not include the DB2 database driver dependency.
+If you want to use DB2 for development/testing when running locally, you can specify the `local-dev-db2` Maven profile when building.
+The following command will include the DB2 driver dependency in the jar:
+```
+$ ./mvnw -s .settings.xml clean package -Plocal-dev-db2
+```
+You can follow the steps in the [DB2 on Mac ARM64](https://github.com/spring-cloud/spring-cloud-dataflow/wiki/DB2-on-Mac-ARM64#running-dataflow-locally-against-db2) Wiki to run DB2 locally in Docker with Dataflow pointing at it.
```
[the remark this answers is not in the document]
Comment (onobc) [reply README.md:123]: This url resolves for me https://github.com/spring-cloud/spring-cloud-dataflow/wiki/DB2-on-Mac-ARM64#running-dataflow-locally-against-db2 
or are you talking about some content in that wiki doc?

[the remark this answers is not in the document]
Comment (cppwfs) [reply README.md:123]: Sorry, yes its the content.   This command shows the error: `docker run --name test-DB2 --hostname test-DB2 -d -p 1433:1433 -e ACCEPT_EULA=Y -e DB2_SA_PASSWORD=DB2Server_RootPassword1 mcr.microsoft.com/DB2/server:2022-latest:   It doesn't like the `/DB2/`.

[the remark this answers is not in the document]
Comment (onobc) [reply README.md:123]: Ahhh the password needs to be in quotes. You can see what it is for MSSQL - I will update now. Thanks

[the remark this answers is not in the document]
Comment (onobc) [reply README.md:123]: Wiki is update - great catch @cppwfs . Thank you for reading the wiki!
