### PR TITLE
Make Sure OAuth2 token is refreshed as needed

### LINKED ISSUE #3894: DataFlowClient does not renew Oauth access token when expired.
The dataflow task launcher sink connects to the server running on PCF, creating a service key that includes client id, client secret and the token url.  At first the connection is successful. Over time, we start to see UnAuthorized errors when launching a task.  

The premise is that he token expires and is not refreshed or a new access token requested. This is needed since the sink process runs indefinitely.  

```
...
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] 2020-04-20 10:01:58.568 ERROR 13 --- [pool-3-thread-1] o.s.c.s.a.t.l.d.s.LaunchRequestConsumer : Unauthorized
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Unauthorized
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:74) ~[spring-cloud-dataflow-rest-client-2.4.2.RELEASE.jar:2.4.2.RELEASE]
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:785) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:743) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:677) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:615) ~[spring-web-5.2.3.RELEASE.jar:5.2.3.RELEASE]
2020-04-20T15:31:58.568+05:30 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.dataflow.rest.client.TaskTemplate.currentTaskExecutions(TaskTemplate.java:230) ~[spring-cloud-dataflow-rest-client-2.4.2.RELEASE.jar:2.4.2.RELEASE]
```

### PR DESCRIPTION
**Pull request by dturanski**
This resolves #3894 Given DataFlowClientProperties `authentication.token-uri, authentication.client-id, authentication.client-secret` Will refresh the auth token whenever a request gets a 401 status.

### CODE REVIEW

File: spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientAutoConfiguration.java [hunk 1]
```diff
@@ -139,28 +148,124 @@ public StreamBuilder streamBuilder(DataFlowOperations dataFlowOperations){
...
+	@ConditionalOnProperty(prefix = DataFlowPropertyKeys.PREFIX + "client.authentication", name = "client-id")
+	@EnableConfigurationProperties(DataFlowClientProperties.class)
+	static class DataFlowClientConfiguration {
+
+		private static Log logger = LogFactory.getLog(DataFlowClientConfiguration.class);
+
+		private static final String DEFAULT_REGISTRATION_ID = "default";
+
+		@Bean
+		public DataFlowOperations dataFlowOperations(@Nullable RestTemplate restTemplate,
```
Comment (jvalkeal) [inline spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientAutoConfiguration.java:161]: We should not create template here as it's already done above in its own method and we also need ConditionalOnMissingBean as it's done there.

File: spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientAutoConfiguration.java [hunk 2]
```diff
@@ -139,28 +148,124 @@ public StreamBuilder streamBuilder(DataFlowOperations dataFlowOperations){
...
+			@Override
+			public ClientHttpResponse intercept(HttpRequest httpRequest, byte[] bytes, ClientHttpRequestExecution execution) throws IOException {
+				return retryTemplate.execute(retryContext -> {
+					httpRequest.getHeaders().add("Authorization",
+							OAuth2AccessToken.TokenType.BEARER.getValue() + " " + this.getTokenValue());
+					logger.debug("Token issued " + oAuth2AccessTokenResponse.getAccessToken().getIssuedAt() +
+							" expires: " + oAuth2AccessTokenResponse.getAccessToken().getExpiresAt());
+					ClientHttpResponse response = execution.execute(httpRequest, bytes);
+					logger.debug(response.getStatusCode());
+					if (response.getStatusCode().equals(HttpStatus.UNAUTHORIZED)) {
```
Comment (jvalkeal) [inline spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/config/DataFlowClientAutoConfiguration.java:246]: This is a problematic as you may get unauthorized even with valid access token and then retry template, afaik does it things 3 times on default. With client credentials flow you only care about if token has expired when to choose refresh it.

**Comment by jvalkeal** [comment]
lgtm :)
