### PR TITLE
[1.7.x] Update Stream DSL after rollback

### LINKED ISSUE #2636: Stream rollback doesn't update the DSL
When a stream is rollback, its DSL is not updated based on the release manifest data. Because of this, the stream DSL still points to the older version's DSL text.

Steps to reproduce:

```
dataflow:>stream create a1 --definition "time | log"
Created new stream 'a1'
dataflow:>stream deploy a1
Deployment request has been sent for stream 'a1'
dataflow:>stream list
╔═══════════╤═════════════════╤═════════════════════════════════════════╗
║Stream Name│Stream Definition│                 Status                  ║
╠═══════════╪═════════════════╪═════════════════════════════════════════╣
║a1         │time | log       │The stream has been successfully deployed║
╚═══════════╧═════════════════╧═════════════════════════════════════════╝

dataflow:>stream update a1 --properties "app.log.log.expression='Updated'"
Update request has been sent for the stream 'a1'
dataflow:>stream list
╔═══════════╤═══════════════════════════════════╤═════════════════════════════════════════╗
║Stream Name│         Stream Definition         │                 Status                  ║
╠═══════════╪═══════════════════════════════════╪═════════════════════════════════════════╣
║a1         │time | log --log.expression=Updated│The stream has been successfully deployed║
╚═══════════╧═══════════════════════════════════╧═════════════════════════════════════════╝
dataflow:>stream rollback a1
Rollback request has been sent for the stream 'a1'
dataflow:>stream list
╔═══════════╤═══════════════════════════════════╤═════════════════════════════╗
║Stream Name│         Stream Definition         │           Status            ║
╠═══════════╪═══════════════════════════════════╪═════════════════════════════╣
║a1         │time | log --log.expression=Updated│The stream is being deployed.║
╚═══════════╧═══════════════════════════════════╧═════════════════════════════╝

```

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Change the rollback method to return rolledback release
  - Use RollbackRequest instead of deprecated one
  - Update the stream DSL after the rollback is complete
  - Add test for update after rollback
  - Fix rollbackStream service test
  - Fix NPE on release during rollback

Resolves #2636

### CODE REVIEW

File: spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java [hunk 1]
```diff
@@ -545,8 +545,8 @@ public Release upgradeStream(String streamName, PackageIdentifier packageIdentif
 	 * @param streamName the name of the stream to rollback
 	 * @param releaseVersion the version of the stream to rollback to
 	 */
-	public void rollbackStream(String streamName, int releaseVersion) {
-		this.skipperClient.rollback(streamName, releaseVersion);
+	public Release rollbackStream(String streamName, int releaseVersion) {
```
Comment (ilayaperumalg) [inline spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/stream/SkipperStreamDeployer.java]: This isn't an API change and I believe this is OK to do it for the point release (given this is only used inside the service API - at the SkipperStreamDeployer)
