### PR TITLE
RestControllerAdvice logs error message only

### LINKED ISSUE #741: Very long stack trace for 'NoSuchStreamDefinitionException'
There is no need for a thee screenful exception if a stream definition is not found and an ERROR level message. This pollutes the log, in particular as the UI calls the stream endpoint to eagerly check if the stream name has already been used.

```
2016-06-28 07:21:35.897 ERROR 6498 --- [nio-9393-exec-7] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

org.springframework.cloud.dataflow.server.repository.NoSuchStreamDefinitionException: Could not find stream definition named ticktock
	at org.springframework.cloud.dataflow.server.controller.StreamDefinitionController.display(StreamDefinitionController.java:201) ~[spring-cloud-dataflow-server-core-1.0.0.BUILD-SNAPSHOT.jar!/:1.0.0.BUILD-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_65]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_65]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_65]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_65]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
```

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- For the exceptions that are handled explicitly, the error is logged with the error message only.
The exception with the stacktrace is thrown only for any other Server exceptions that are not explicitly handled.

This resolves #741

### CODE REVIEW

File: stream-applications-rabbit-maven [hunk 1]
```diff
@@ -0,0 +1,46 @@
+source.file=maven://org.springframework.cloud.stream.app:file-source-rabbit:1.0.0.BUILD-SNAPSHOT
```
Comment (markpollack) [inline stream-applications-rabbit-maven]: i think this file is here by mistake.

File: spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RestControllerAdvice.java [hunk 2]
```diff
@@ -99,13 +106,25 @@ public VndErrors onUnprocessableEntityException(Exception e) {
...
 	}
 
-	private String logError(Throwable t) {
+	private String logError(Exception e) {
+		logger.error("Caught exception while handling a request: " + getExceptionMessage(e));
+		return e.getClass().getSimpleName();
+	}
+
+	private String logTrace(Throwable t) {
 		logger.error("Caught exception while handling a request", t);
```
Comment (markpollack) [inline spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RestControllerAdvice.java]: This is not at the trace level.

File: spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RestControllerAdvice.java [hunk 3]
```diff
@@ -99,13 +106,25 @@ public VndErrors onUnprocessableEntityException(Exception e) {
...
 		return new VndErrors(logref, msg);
 	}
 
-	private String logError(Throwable t) {
+	private String logError(Exception e) {
+		logger.error("Caught exception while handling a request: " + getExceptionMessage(e));
+		return e.getClass().getSimpleName();
+	}
+
+	private String logTrace(Throwable t) {
```
Comment (markpollack) [inline spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RestControllerAdvice.java]: This is not logging at the trace level

File: spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RestControllerAdvice.java [hunk 4]
```diff
@@ -73,17 +74,23 @@ public VndErrors onException(Exception e) {
 	@ResponseStatus(HttpStatus.CONFLICT)
 	@ResponseBody
 	public VndErrors onConflictException(Exception e) {
+		if (logger.isTraceEnabled()) {
```
Comment (markpollack) [inline spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/RestControllerAdvice.java]: logging the error first would probably be better ordering, so that one sees the message and then the stack trace.

**Comment by markpollack** [comment]
Updated to log warning level messages for all known exceptions, put stack trace at trace level after error message log.

```
2016-06-28 21:47:36.686  WARN 38144 --- [nio-9393-exec-2] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request: Could not find stream definition named ticktoc
2016-06-28 21:47:37.150  WARN 38144 --- [nio-9393-exec-4] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request: Could not find stream definition named ticktock
```

is what appears now when using the UI

**Comment by markpollack** [comment]
Merged as
